Linaro/uadk

- Makefile.am
libhisi_hpre_la_LIBADD is overlapped
> wd: remove duplicated libhisi_hpre_la_LIBADD parts

- conf.sh
By default headers are copyied to /usr/local/include,
add --includedir=/usr/local/include/uadk
For example app.c #include <uadk/wd.h>
> conf.sh: add --includedir

- test/hisi_zip_test/test_lib.c
- test/sched_sample.c
hzhuang1@j13-d06-02:~/warpdriver$ sudo ./test/hisi_zip_test/test_sva_perf  -l 1000 -q 16 -m 1
Couldn't open file /sys/kernel/debug/tracing/events/iommu/dev_fault/id
Compress bz=512000 nb=1000×10, speed=7609.6 MB/s (±0.0% N=1) overall=7551.6 MB/s (±0.0%)
After running commands above with a couple of times, a new error is reported.
hzhuang1@j13-d06-02:~/warpdriver$ sudo ./test/hisi_zip_test/test_sva_perf  -l 1000 -q 8 -m 1
Couldn't open file /sys/kernel/debug/tracing/events/iommu/dev_fault/id
qm send is err(-16)!
hzhuang1@j13-d06-02:~/warpdriver$ sudo dmesg | tail -n 5
[  120.114938] FAT-fs (sda1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[  120.421400] Adding 64142332k swap on /dev/sda3.  Priority:-2 extents:1 across:64142332k 
[  125.109418] hns3 …
> Fix zip poll

- test/hisi_sec_test/test_hisi_sec.c
We can't get the result of the sec test if the return value always
is zero. This patch adds the return value to help get the result.
> test: sec: Adds the return value of the test main function

- test/hisi_zip_test/test_lib.c
req->cb and req->cb_param must be filled. Otherwise, asynchronous operation
will be blocked.
> test/zip: fix to add cb and cb_param

- wd_aead.c
Do not use absolute path, otherwise shared library load fail.
Instead, shared library path should rely on environment path.
log:
openat(AT_FDCWD, "/usr/lib/wd/libhisi_sec.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT
(No such file or directory)
> wd: aead: fix loading share library

- test/hisi_zip_test/Makefile.am
- test/hisi_zip_test/sva_file_test.c
- test/hisi_zip_test/test_lib.c
- test/hisi_zip_test/test_lib.h
- test/hisi_zip_test/test_sva_perf.c
- test/sched_sample.c
1.add file stdin stdout for file compress/decompress.
2.support multiple thread.
3.fix sched_sample printf to WD_ERR.
sample test:
(1)block mode, sync mode, only support 8M file max:
./test_sva_perf -F < file > out.gz
./test_sva_perf -F -d < out.gz > file
(2)stream mode, support (u32) 4GB-1.
./test_sva_perf -F -S < file > out.gz
./test_sva_perf -F -S -d < out.gz > file
(3)support multi-therad, use -t num.
./test_sva_perf -F -t 32 < file > out.gz
./test_sva_perf -F -d -t 32 < out.gz > file
(4)block mode, async mode, only support 8M file max:
./test_sva_perf -F -m 1 < file > out.gz
./test_sva_perf -F -d -m 1 < out.gz > file
full example:
dd if=/dev/urandom of=origin bs=10K count=1
md5sum origin > ori.md5
./test_sva_perf -F < origin > out.gz
./test_sva_perf -F -d < out.gz > origin
md5sum -c …
> wd: test: test_sva_perf support file comp testcase

- Makefile.am
- include/wd_alg_common.h
- include/wd_cipher.h
- test/hisi_hpre_test/test_hisi_hpre.c
- test/hisi_sec_test/Makefile.am
- test/hisi_sec_test/test_hisi_sec.c
- test/sched_sample.c
- wd_aead.c
- wd_cipher.c
- wd_comp.c
- wd_dh.c
- wd_digest.c
- wd_rsa.c
The sec cipher test used the stub that only surport the simple case.
Tish patch add the scheudle API to cipher.
Signed-ff by: Zhenkun Mi <mi_zhenkun@163.com>
> test: sec: Use the schedule API replace the stub of cipher test.

- drv/hisi_qm_udrv.c
- test/hisi_sec_test/test_hisi_sec.c
For support the multiple ctxs test case, the test app
support the ctx option for user.We can input the value
to control app alloc multi hareware queue resource and
procsess the data.
Signed-ff by: Zhenkun Mi <mi_zhenkun@163.com>
> test: sec: Add the ctx num para in sec test app

- test/hisi_zip_test/test_sva_perf.c
Commit dff36ddf moved checking contexts out of init_ctx_config().
So in run_one_test(), this checking procedure should be applied.
Otherwise, app will fail with invalid list pointer.
> test: zip: fix checking contexts for run_one_test()

- test/hisi_zip_test/test_lib.c
- test/hisi_zip_test/test_lib.h
- test/hisi_zip_test/test_sva_perf.c
The operation of handling kill signal is missing. Append it back to fix
the issue.
> test: zip: fix to accept kill signal

- test/hisi_sec_test/test_hisi_sec.c
"commit 55e081e4" tries to make ctx_num as a configurable parameter.
But it doesn't consider the case if ctx parametr is not set by user.
So fix it with default value.
> test: sec: fix on uninitialized ctx_num

- INSTALL
Since the app is renamed, update it in INSTALL document.
> doc: INSTALL: rename test_sva_perf to zip_sva_perf

- test/sanity_test.sh
As zip test APP name has changed, fix it to new name zip_sva_perf.
Also fix block size to 8192 to avoid test warning.
> wd/test: Fix zip test app name in sanity_test.sh

- drv/hisi_qm_udrv.c
- include/hisi_qm_udrv.h
Uadk qm manage base the qp, not the ctx, the old API
should be remove.
> drv: qm: rm alloc and free ctx func which isn't used

- drv/hisi_qm_udrv.c
If hardware doorbell information is not difference from
"hisi_qm_v2" in later version, there is no need to add
qm version string, default use "hisi_qm_v2".
Signed-off-by: Hui tang <tanghui@8237897913@qq.com>
> wd/qm: Add qm version defualt type.

- test/hisi_sec_test/test_hisi_sec.c
Remove duplicated log to have a clean log espacially for doing multiple
threads test.
> test: sec: Remove duplicated log

- drv/hisi_qm_udrv.c
- include/hisi_qm_udrv.h
- wd_aead.c
- wd_cipher.c
- wd_digest.c
Remove locks in aead/cipher/digest async APIs to qm send/recv functions.
Performance of async one thread/ctx will improve:
numactl --cpubind 1 --membind 1  test_hisi_sec --perf --async --pktlen 1024 \
--block 1024 --blknum 100000 --times 100000 --multi 1 --ctxnum 1
Former:
time_used:122203 us, send task num:100000
Async mode Pro-51002, thread_id-51002, speed:818310.500000 ops, Perf: 818310 KB/s
Improve to:
time_used:39032 us, send task num:100000
Async mode Pro-60956, thread_id-60956, speed:2562000.500000 ops, Perf: 2562000 KB/s
> wd: Remove lock in aead/cipher/digest async APIs

- test/hisi_sec_test/test_hisi_sec.c
In the cipher sync test case, the data copy will overflow
when the pktlen bigger than the template ptext size. The
patch will user the min(pktlen, ptext_size) to be the copy
len.
> sec: test: Fix the bug when copy the cipher data

- drv/hisi_qm_udrv.c
- drv/hisi_sec.c
- include/hisi_qm_udrv.h
- include/wd_alg_common.h
- include/wd_cipher.h
- test/hisi_sec_test/test_hisi_sec.c
Add the sgl data mode of cipher, the process will be not changed
if the req's data format is 0. Of course, user can config the
data format to be 1, and create the sgl list to use the sgl mode
of cipher.
> sec: cipher: Add cipher SGL sqe mode

- drv/hisi_sec.c
modify BD3 structure alignment from "#pragma pack(4)" to "__attribute__((packed, aligned(4)))"
> wd/sec: modify BD3 structure alignment

- drv/hisi_sec.c
- test/hisi_sec_test/test_hisi_sec.c
We should reback the sgl after using.
> sec: cipher: Add put sgl to the sgl poll in cipher recieve V3

- test/hisi_sec_test/test_hisi_sec.c
- wd_cipher.c
The buff support the sgl of pbuff mode, when sgl mode,
the buff should be created and free by different mode in test.
Now only modify the onece test case of cipher.
> sec: cipher: Modify buff filling in cipher test

- drv/hisi_qm_udrv.c
- test/hisi_sec_test/test_hisi_sec.c
1.Add sgl mode in all the sec cipher test case.
2.Fixed the sgl put bug
> test: sec: Add cipher sync&async sgl mode

- README
Introduce different documents in README. Let user know how to work with
UADK.
> docs: introduce documents in README

- drv/hisi_qm_udrv.c
- drv/hisi_sec.c
- include/hisi_qm_udrv.h
- include/wd_alg_common.h
- include/wd_cipher.h
- test/hisi_sec_test/test_hisi_sec.c
- wd_cipher.c
The hw support two data mode, the pbuff and sgl. This patch add
the cipher sgl mode as follows:
1. In the wd cipher, add the sgl struct in wd_cipher_req for user.
2. In the sec diver, transform the wd sgl to hw sgl struct.
3. In the qm, add the sgl pool manage, include create, destroy, get
and put.
4. In the test sec, add the sgl mode para to test the sgl buff to BD.
> wd: sec: Add cipher sgl mode

- Makefile.am
- drv/hisi_comp.c
When UADK sends the last SQE to hardware accelerator, consumer may
be 0 but producer still records data of previous SQE.
Signed-off-by: wenkai lin <linwenkai755@qq.com>
> drv: hisi_comp: fix condition on parse_zip_sqe return

- drv/hisi_sec.c
- include/wd.h
- include/wd_aead.h
- include/wd_digest.h
- test/hisi_sec_test/test_hisi_sec.c
- wd_aead.c
- wd_cipher.c
- wd_digest.c
1、The digest out buff is not support the sgl mode.
2、The aead src buff len should add the payload and head.
> drv: sec: Fixed bugs in sec sgl buffer mode

- drv/hisi_sec.c
In the Kunpeng930, the hardware have supported 0 input length
for AEAD CCM/GCM mode algorithms.
> wd/sec: add CCM/GCM mode 0 input length for SEC

- drv/hisi_qm_udrv.c
- drv/hisi_sec.c
- include/hisi_qm_udrv.h
The cipher flow mode should update iv after recieving
msg. This patch add the copy from sgl buff to iv.
> drv: qm: Add the cipher flow mode in sgl

- drv/hisi_qm_udrv.c
- drv/hisi_sec.c
- include/hisi_qm_udrv.h
- include/wd_aead.h
- include/wd_alg_common.h
- include/wd_cipher.h
- include/wd_digest.h
- test/hisi_sec_test/test_hisi_sec.c
The name wd_sgl is same with the v1 hardware sgl
struct name. In uadk, it is the datalist of user
input.
> drv: qm: Change the wd_sgl to wd_datalist

- include/wd_alg_common.h
- wd_aead.c
- wd_cipher.c
- wd_comp.c
- wd_dh.c
- wd_digest.c
- wd_ecc.c
- wd_rsa.c
- wd_util.c
Running SEC taskes with multiple threads could gain better performance
in synchronous mode.
numactl --cpubind 1 --membind 1  test_hisi_sec --perf --sync --pktlen 1024 \
--block 1024 --blknum 100000 --times 100000 --multi 8 --ctxnum 8
Former:
time_used:675324 us, send task num:800000
Sync mode avg Pro-168651, thread_id-168651, speed:1184616.625000 ops, Perf: 1184616 KB/s
Improved to:
time_used:359002 us, send task num:800000
Sync mode avg Pro-150288, thread_id-150288, speed:2228399.750000 ops, Perf: 2228399 KB/s
numactl --cpubind 1 --membind 1  test_hisi_sec --perf --sync --pktlen 1024 \
--block 1024 --blknum 100000 --times 100000 --multi 16 --ctxnum 16
Former:
time_used:606475 us, send task num:1600000
Sync mode avg Pro-168662, thread_id-168662, speed:2638196.250000 ops, Perf: 2638196 …
> wd: replace mutex lock by spin lock in ctx structure

- drv/hisi_qm_udrv.c
- include/hisi_qm_udrv.h
- include/wd.h
- wd.c
- wd_aead.c
- wd_cipher.c
- wd_digest.c
While app run on ACC PF and VF in user space including
VM (vSVA) user space, they can be notified as RAS resetting.
Afer that, app can request queue end release the old queue, and
do the task on the new queue again.
> drv: qm: Add support of user space (v)SVA task resetting

- drv/hisi_qm_udrv.c
- test/hisi_sec_test/test_hisi_sec.c
1. the data len bigger than 8M return null.
2. the data buff is null, proc next.
> drv: qm: Add the abnormal process in get hw pool

- Makefile.am
Add dependency in Makefile. Fix the issue in concurrent build. Verifyed
by "make -j32".
> Makefile: fix to build in concurrent mode

- Makefile.am
While invoke "make -j64" to build UADK in static mode, there's a still
failue issue.
Need to apply dependencies on static libraries.
> Makefile: fix concurrent build issue for param 64

- test/hisi_zip_test/sva_file_test.c
- test/hisi_zip_test/test_lib.c
- test/hisi_zip_test/test_lib.h
- test/hisi_zip_test/test_sva_perf.c
Several changes to the zip_sva_perf test:
* Small fixes and remove unused code.
* Restore the I/O page fault statistics.
* Most importantly, restore the TLB test (-k tlb), which allows to explicitly trigger invalid page faults with the zip device and is important to testing the kernel SVA infrastructure.
* Finish merging zip_sva_perf with test_bind. Instead of going a different path with the -r (create child processes) and -k (inject faults) options, use a single code path.
Please let me know if I should split into multiple pull requests
> Fixes and cleanup for the zip_sva_perf test

- drv/hisi_hpre.c
- drv/hisi_qm_udrv.c
- include/drv/wd_ecc_drv.h
- include/hisi_qm_udrv.h
Add encrypt and decrypt processing when message more than 4096bits.
when message more than 4096bits, Kupeng 930 hardware has not realize
the whole process of sm2 algorithm encrypt and decrypt, so drive
realize some process.
> wd/hpre: support sm2 encrypt/decrypt

- drv/hisi_sec.c
1. wd/sec: modify cipher CTR mode spec
Kunpeng930's CTR mode already supports 1-Byte alignment
2. wd/sec: modify aead alg parameter
Kunpeng920 not support ccm-sm4
> wd/sec: modify sec driver alg parameter

- drv/hisi_sec.c
- include/wd_aead.h
- include/wd_cipher.h
- wd_aead.c
- wd_cipher.c
- wd_digest.c
fixup spelling error on comments and function name.
> uadk/sec: fix typo issue

- drv/hisi_qm_udrv.c
fix lock released problem in qm send during task resetting.
> drv/qm: fix lock released problem in qm send

- Makefile.am
- include/uacce.h
- include/wd.h
- include/wd_alg_common.h
- wd_mempool.c
To avoid page faults in the kernel, uadk offers this memory pool. memory
allocated from this pool will not have page faults at all.
The usage of this pool can be got from wd.h
Basic implementation of this pool is to allocate memory from huge pages or
memory which has been pinned.
Signed-off by: Zhenkun Mi <mi_zhenkun@163.com>
Signed-off by: Sihang Chen <chenxihang1@huawei.com>
> uadk: Add a memory pool in libwd

- v1/wd_bmm.c
v1/wd_bmm.c: In function ‘wd_blkpool_create’:
v1/wd_bmm.c:124:29: error: ‘qinfo’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
if (!sp->br.alloc && !qinfo->iommu_type)
^
v1/wd_bmm.c:95:17: note: ‘qinfo’ was declared here
struct q_info *qinfo;
^
cc1: all warnings being treated as errors
Makefile:756: recipe for target 'v1/wd_bmm.lo' failed
make[2]: *** [v1/wd_bmm.lo] Error 1
> wd: v1: fix uninitialized variable in BMM

- conf.sh
"--with-uadk_v1" configuration is unnecessary. Since both uadk v1 and v2
are built into libwd at the same time.
> cfg: remove uadk_v1 in configuration

- Makefile.am
wd_common.h is not copied to include when make install
As a result, openssl-uadk is build error.
/usr/local/include/uadk/wd_alg_common.h:7:23: fatal error: wd_common.h: No such file or directory
> wd: add missing header file in make install

- include/wd.h
- test/wd_mempool_test.c
- wd_mempool.c
Change prefix on blkpool from wd_pool_ to wd_blockpool_.
> wd: mem: change prefix on blkpool

- Makefile.am
Fix openssl-uadk build error.
uadk_ecc.c:8:25: fatal error: uadk/wd_ecc.h: No such file or directory
> wd: add missing header file wd_ecc.h

- include/wd.h
- test/hisi_hpre_test/Makefile.am
- test/hisi_zip_test/Makefile.am
- wd.c
Get device supporting the algorithm with smallest numa distance
to current numa node
Example:
dev = wd_get_accel_dev("digest");
> wd: add wd_get_accel_dev

- include/wd.h
- wd.c
wd_free_list_accels free all memory, so wd_get_accel_dev returns
a cloned dev, which should be freed after usage
> wd: wd_get_accel_dev returns cloned uacce_dev

- drv/hisi_comp.c
- drv/hisi_sec.c
Print lots useless info when run multi async mode.
Signed-off-by: linwenkai <linwenkai6@hisilicon.com>
> drv: sec:avoid print info when device is busy

- wd_aead.c
- wd_digest.c
Fix the heap buffer overflow by asan checking.
> wd: fix the heap buffer overflow

- v1/drv/hisi_sec_udrv.c
- wd_aead.c
The AEAD's assoc_data not need 16-alignment, so delete the
assoc_data parameter checking.
> wd/aead - fix assoc_data parameter checking

- v1/drv/hisi_qm_udrv.c
since the HW sgl is pre-allocated, it will only be returned to the
HW sgl pool after use, and the sgl parameters will not be cleared.
After multiple consecutive multiplexing, the HW sgl parameters will
overflow, cause HW parsing error.
Therefore, it need to add the total length of the sgl chain according
to the length of the two target sgl,rather than the superpostion of the
total length.
> wd/sgl/v1: modify sgl chain length

- test/hisi_sec_test/Makefile.am
- test/hisi_zip_test/Makefile.am
./autogen.sh
test/hisi_sec_test/Makefile.am:5: warning: source file '../sched_sample.c' is in a subdirectory,
test/hisi_sec_test/Makefile.am:5: but option 'subdir-objects' is disabled
test/hisi_zip_test/Makefile.am:5: warning: source file '../sched_sample.c' is in a subdirectory,
test/hisi_zip_test/Makefile.am:5: but option 'subdir-objects' is disabled
> uadk: fix Makefile subdir

- Makefile.am
- docs/wd_environment_variable
- include/sched_sample.h
- include/wd.h
- include/wd_comp.h
- include/wd_util.h
- test/hisi_zip_test/test_lib.h
- test/hisi_zip_test/test_sva_perf.c
- test/hisi_zip_test/testsuit.c
- wd_comp.c
- wd_util.c
Make UADK to parse environment variable to get information. The basic
goal is to make UADK easier to use.
"--env" is the parameter to enable environment variable in zip_sva_perf
test case. Up to now, the feature of environment variable is enabled in
synchronous mode.
> wd: add environment variable

- test/sanity_test.sh
Use different way to not output console. Since sometimes "&>" may report
error while CI runs sanity_test script file.
> test: sanity: rewrite for not outputing console

- test/sanity_test.sh
Abadon to capture exit code in run_cmd() since it may result in error
in CI.
> test: sanity: abadon to capture exit code in run_cmd

- test/sanity_test.sh
Since it may result in error in CI.
> test: sanity: avoid to use run_cmd for security test

- include/wd_cipher.h
- test/hisi_sec_test/test_hisi_sec.c
- test/sched_sample.c
- wd_cipher.c
- wd_util.c
1.Adapt cipher to init ctx with environment variable
2."--use_env" for test_hisi_sec to enable environment variable.
3.Fix some problem under default scenario.
More algorithm modules will be adapted to use environment variable  later.
> wd: add cipher environment variable

- include/wd_aead.h
- include/wd_cipher.h
- include/wd_comp.h
- include/wd_dh.h
- include/wd_digest.h
- include/wd_ecc.h
- include/wd_rsa.h
- test/hisi_sec_test/test_hisi_sec.c
- test/hisi_zip_test/test_lib.c
- test/hisi_zip_test/testsuit.c
- wd_aead.c
- wd_cipher.c
- wd_comp.c
- wd_dh.c
- wd_digest.c
- wd_ecc.c
- wd_rsa.c
Now the schedule design three patameters. 'type' is not a common setting.
'numa_id' is a patameter decided by users. So assign it in create 'sess'.
'mode' shouldn't be unchangeable, so assign it according to the interface
calling by user than than in create 'sess'.
Signed-off-by: Yang Shen <youngershen@foxmail.com>
> uadk: schedule - modify schedule parameter assignments

- test/hisi_zip_test/test_lib.c
- test/hisi_zip_test/test_lib.h
- test/hisi_zip_test/test_sva_perf.c
fix build error:
test_lib.c:1324:9: error: 'tdatas' may be used uninitialized in this function
test_sva_perf.c:646: undefined reference to `comp_file_test'
Signed-off-by: Yang Shen <youngershen@foxmail.com>
> uadk: test/hisi_zip_test - fix build error

- include/wd_aead.h
- include/wd_digest.h
- include/wd_util.h
- test/hisi_sec_test/test_hisi_sec.c
- test/sanity_test.sh
- wd.c
- wd_aead.c
- wd_cipher.c
- wd_comp.c
- wd_digest.c
- wd_util.c
1.Adapt cipher to init ctx with environment variable
2.Fix some bug
3.modify default value
4.Remove WD_ALG_NUMA
> wd: env: support digest and aead

- drv/hisi_sec.c
The CTR counter is 32bit rollover default on Kunpeng930.
But the NIST standard is 128bit rollover. it cause the
testing failed, so need to fix it.
> uadk: sec - fix aes-ctr test failed

- wd_aead.c
- wd_cipher.c
- wd_comp.c
- wd_digest.c
when long packages and short packages are mixedly
sent, short packages will cause the waiter of the
long packages wake up early, resulting in an
increase in CPU usage.
> wd/sec: modify the synchronization mode poll

- v1/test/bmm_test/Makefile.am
- v1/test/hisi_hpre_test/Makefile.am
- v1/test/hisi_trng_test/Makefile.am
- v1/test/hisi_zip_test/Makefile.am
- v1/test/hisi_zip_test_sgl/Makefile.am
- v1/test/test_mm/Makefile.am
The makefile expression of the test tools in v1 are not uniform.
this patch is used to correct this difference.
Signed-off-by: Longfang Liu <longfang.liu@foxmail.com>
> test/v1: cleanup makefile's expression

- Makefile.am
la files are generated in both static library or dynamic library build.
In different build, la files are different. But la files are always
installed into library directory. It will confuse test cases.
Now delete la files before installing libraries.
> wd: avoid to install la files

- drv/hisi_sec.c
- include/drv/wd_aead_drv.h
- include/wd_aead.h
- include/wd_cipher.h
- include/wd_digest.h
- test/hisi_sec_test/test_hisi_sec.c
- wd_aead.c
- wd_cipher.c
- wd_digest.c
1. Fix iv bytes align checking for skcipher.
2. Optimize the digest length checking. Combine the two jugement
branchs into one.
3. Modify the dfx message.
> cipher/v2 - fix some tiny bugs of SEC

- drv/hisi_qm_udrv.c
- include/wd.h
- uadk_benchmark/Makefile.am
- uadk_benchmark/sec_uadk_benchmark.c
- uadk_benchmark/sec_wd_benchmark.c
- uadk_benchmark/uadk_benchmark.c
- uadk_benchmark/uadk_benchmark.h
Remove the alignment operation of the number of received and
send packets in the uadk benchmark, and calculate the performance
according to the time stop method.
Reduce the impact of test tool code on performance by optimizing
the statistical method of test tools.
Signed-off-by: Liulongfang <longfang.liu@foxmail.com>
> uadk/benchmark: modify test tools data cal

- wd_cipher.c
There is no 'iv' in XTS mode, so there is no need to verify
the 'iv' length for XTS mode.
Signed-off-by: Yang Shen <shenyang39@huawei.com>
> cipher: fix wrong iv length check

- wd_util.c
1.reduce the number of queries to find effective resources from the
resource pool by retaining the index of the effective resource
obtained last time.
2.bugfix some coding style
Signed-off-by: Liulongfang <longfang.liu@foxmail.com>
> wd: bugfix msg pool idx

- test/sanity_test.sh
Cut down the size from 64MB to 16MB. To avoid an unnecessary error.
> test: zip: cut down the size of test text file

- test/sanity_test.sh
Since the self test may be blocked in CI, just diable it.
While it's blocked, CPU usage is full. It seems that polling threads can
not be ended.
> test: disable zip self test in sanity scripts

- v1/wd.c
- v1/wd_aead.c
get_dev_info should not return flags, it is meaningless.
> wd/v1: fix get_dev_info return value

- Makefile.am
- include/wd_aead.h
- include/wd_alg_common.h
- include/wd_cipher.h
- include/wd_comp.h
- include/wd_dh.h
- include/wd_digest.h
- include/wd_ecc.h
- include/wd_rsa.h
- include/wd_sched.h
- include/wd_util.h
- sample/uadk_sample.c
- test/hisi_hpre_test/test_hisi_hpre.c
- test/hisi_sec_test/test_hisi_sec.c
- test/hisi_zip_test/test_lib.c
- test/hisi_zip_test/test_lib.h
- test/hisi_zip_test/testsuit.c
- test/wd_mempool_test.c
- uadk_benchmark/sec_uadk_benchmark.c
- wd_aead.c
- wd_cipher.c
- wd_comp.c
- wd_dh.c
- wd_digest.c
- wd_ecc.c
- wd_rsa.c
- wd_sched.c
- wd_util.c
Since the current default scheduling method will have a serious
performance bottleneck under multi-threading, it is necessary
to update the scheduling implementation method.
1.Update the interface of the RR scheduler
2.Update the usage of scheduler in ALG API
3.Update the uadk test tools
Signed-off-by: Liulongfang <longfang.liu@foxmail.com>
> wd/sched: update the RR scheduler inside UADK

- wd_cipher.c
Due to the modification of the decoupling of the scheduler
and the ALG API, the interface mode check function was mistakenly
deleted.
> cipher: repair ALG interface mode check

- drv/hisi_sec.c
1. Add out_bytes checking for digest alg. and modify some log
information.
2. Optimize the in_bytes length checking.
> hisi-sec: bugfix for out_bytes checking

- uadk_tool/Makefile.am
- uadk_tool/sec_wd_benchmark.c
- uadk_tool/uadk_benchmark.c
In the No-SVA scenario, the user's business data needs to be copied
from the user memory to the block memory allocated by the user mode
through the copy method.
After the business execution is completed, it needs to be copied back.
The test tool should truly reflect the copy operation process.
> uadk/tools: modify NO-SVA test scenario

- v1/wd_util.c
- v1/wd_util.h
If ctx message number is too big, it takes a lot of time
to initialize each cookies and drag performance, so this
patch reduce it from 1024 to 64.
We also found calloc in wd_init_cookie_pool use to much cpu
when it does memset zero, which is not unnecessary, so
replace it with malloc is better.
> uadk: v1: fix for cookie initialization

- uadk_tool/sec_wd_benchmark.c
Fix build warning:
In file included from sec_wd_benchmark.c:3:
uadk_benchmark.h:168:31: note: expected ‘u8 *’ {aka ‘unsigned char *’} but argument is of type ‘char *’
168 | extern void get_rand_data(u8 *addr, int size);
|                           ~~~~^~~~
sec_wd_benchmark.c: In function ‘sec_wd_async_run’:
sec_wd_benchmark.c:613:16: warning: pointer targets in passing argument 1 of ‘get_rand_data’ differ in signedness [-Wpointer-sign]
613 |  get_rand_data(src_data_buf, g_pktlen);
|                ^~~~~~~~~~~~
|                |
|                char *
sec_wd_benchmark.c: In function ‘sec_wd_sync_run’:
sec_wd_benchmark.c:913:16: warning: pointer targets in passing argument 1 of ‘get_rand_data’ differ in signedness [-Wpointer-sign]
913 |  get_rand_data(src_data_buf, g_pktlen);
| …
> uadk_tool: fix build warning of sec_wd_benchmark

- v1/wd_util.c
wd_alloc_id use __atomic_test_and_set to find
an available cookie with zero status,
it may not find a zero cookie with dirty memory,
so cookie status region should be set to zero.
> uadk: v1: fix pool cstatus memset problem

- wd_aead.c
- wd_cipher.c
- wd_comp.c
- wd_dh.c
- wd_digest.c
- wd_ecc.c
- wd_rsa.c
When the initialization of each alg driver failed,
the wd_<alg>_setting.priv should be set to NULL.
Otherwise there will be segment fault when
uninitializing the alg driver.
Signed-off-by: Zhiqi Song <songzhiqi1@huawei.com>
> uadk: bugfix segment fault when uninitializing

- drv/hisi_hpre.c
When these functions are executed successfully,
the caller of these functions will not care about
the value of the data size, so there is no need
to return the data size, just returning a "WD_SUCCESS"
will be fine.
Signed-off-by: Weili Qian <qianweili@huawei.com>
> hisi_hpre: modify the return value of function

- wd_sched.c
In the general scenario, after the scheduler is initialized, the user
wished to use the default scheduling parameters through the default
configuration when initilazing the task session
> wd/sched: modify default sched param

- README
- drv/hisi_comp.c
- drv/hisi_hpre.c
- drv/hisi_qm_udrv.c
- drv/hisi_sec.c
- include/drv/wd_dh_drv.h
- include/drv/wd_ecc_drv.h
- include/drv/wd_rsa_drv.h
- include/hisi_qm_udrv.h
1. modify README
2. In synchronous mode, when multiple threads in a single queue send and
receive messages, if one thread exits the message overtime, other threads
may receive the overtime message, resulting in message misalignment.
Therefore, we need to add the message sequence number check. if it is
not our own sequence number, it means that the message is received
incorrectly and needs to exit.
> add BD id check for sync mode

- drv/hisi_comp.c
- drv/hisi_hpre.c
- drv/hisi_sec.c
- include/drv/wd_aead_drv.h
- include/drv/wd_cipher_drv.h
- include/drv/wd_comp_drv.h
- include/drv/wd_dh_drv.h
- include/drv/wd_digest_drv.h
- include/drv/wd_ecc_drv.h
- include/drv/wd_rsa_drv.h
- include/wd_util.h
- wd_aead.c
- wd_cipher.c
- wd_comp.c
- wd_dh.c
- wd_digest.c
- wd_ecc.c
- wd_rsa.c
- wd_util.c
These patches move some redundant codes to wd_utils from wd_<alg>.c, and remove the unnecessary locks in wd_<alg>.c.
> uadk: some misc fixes

- Makefile.am
Add header file in build file.
> uadk: missing header file after install uadk

- configure.ac
- test/Makefile.am
- test/hisi_hpre_test/Makefile.am
- uadk_tool/Makefile.am
- v1/test/Makefile.am
> Makefile: don't build component if no libz or libcrypto

- README
The detailed building instructions are listed in INTALL. And the simpler one is in README.
While user reads README, he may ignore the full version of building instructions in INSTALL. So remove the simpler one.
> doc: remove build information in README

- ChangeLog
- configure.ac
- docs/maintenance.md
- include/wd_digest.h
- uadk_tool/benchmark/hpre_wd_benchmark.c
- uadk_tool/benchmark/sec_wd_benchmark.c
- v1/wd_comp.c
- v1/wd_comp.h
warpdrive is obsolete, replace it with uadk
> uadk: replace warpdrive with uadk

- v1/wd_util.h
On x86
./cleanup.sh
./autogen.sh
./configure.sh
./v1/wd_util.h:354:2: error: #error "no platform mb, define one before
With this patch, x86 build can be succeed
> v1: fix x86 local build

- configure.ac
UADK only works with openssl 1.1.1x, so add check
> uadk: configure.ac openssl version

- test/hisi_hpre_test/Makefile.am
- test/hisi_zip_test/Makefile.am
- uadk_tool/Makefile.am
Only -lcrypto may fail since no -L
Instead, we can use
$(libcrypto_LIBS): -L/usr/local/lib -lcrypto
$(libcrypto_MOCKA_CFLAGS): -I/usr/local/include
configure.ac
PKG_CHECK_MODULES(libcrypto)
> uadk: Replace -lcrypto with $(libcrypto_LIBS)

- v1/test/hisi_zip_test/Makefile.am
- v1/test/hisi_zip_test/test_hisi_zip.c
- v1/test/hisi_zip_test_sgl/Makefile.am
- v1/test/hisi_zip_test_sgl/wd_zip_test_sgl.c
Both hisi_zip_test and hisi_zip_test_sgl use ../smm.c, which blocks make distclean.
Fixed by #include "../smm.c" in each file.
> v1: fix make distclean

- v1/wd_dh.c
- v1/wd_rsa.c
Before creating ctx, the key bits must be checked. If the key bits is incorrect, return failed.
Signed-off-by: Weili Qian <qianweili@huawei.com>
> uadk/v1: check dh and rsa key bits

- Makefile.am
- docs/wd_alg_init2.md
- docs/wd_design.md
- include/wd.h
- include/wd_alg_common.h
- include/wd_comp.h
- include/wd_util.h
- libwd.map
- libwd_comp.map
- wd.c
- wd_aead.c
- wd_cipher.c
- wd_comp.c
- wd_dh.c
- wd_digest.c
- wd_ecc.c
- wd_rsa.c
- wd_util.c
This is resend for pr #493 , Due to the interface need to compatible 
the expansion, update the wd_comp_init2() parameters.
---------------------------------------------------------------------------
The current uadk initialization process is:
1.Call wd_request_ctx() to request ctxs from devices.
2.Call wd_sched_rr_alloc() to create a sched(or some other scheduler alloc
function if exits).
3.Initialize the sched.
4.Call wd__init() with ctx_config and sched.
Logic is reasonable. But in practice, the step of wd_ request_ Ctx()
and wd_ sched_ rr_alloc() are very tedious. This makes it difficult
for users to use the interface. One of the main reasons for this is
that uadk has made a lot of configurations in the scheduler in order
to provide users with better performance. Based on this …
> uadk - add wd_comp_init2

- wd.c
Build errors happen with GCC 12
wd.c: In function 'wd_is_isolate':
wd.c:193:21: error: the comparison will always evaluate as 'true' for the address of 'dev_root' will never be NULL [-Werror=address]
193 |         if (!dev || !dev->dev_root)
|                     ^
In file included from wd.c:21:
./include/wd.h:131:14: note: 'dev_root' declared here
131 |         char dev_root[PATH_STR_SIZE];
|              ^~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:816: wd.lo] Error 1
Fix by using strlen(dev->dev_root).
Signed-off-by: Thomas Monjalon <thomas@monjalon.net>
> wd: Fix GCC 12 build issue

- Makefile.am
- docs/UADK_framework_expansion_and_modular_dynamic_loading_design.md
- drv/hisi_comp.c
- include/drv/wd_comp_drv.h
- include/wd.h
- include/wd_alg.h
- include/wd_alg_common.h
- include/wd_sched.h
- include/wd_util.h
- libwd.map
- sample/Makefile.am
- test/Makefile.am
- test/hisi_sec_test/Makefile.am
- test/hisi_zip_test/Makefile.am
- wd.c
- wd_alg.c
- wd_comp.c
- wd_sched.c
- wd_util.c
Update the current driver adaptation and usage method, from fixed
use of Hisilicon device driver to automatic registration of the
driver according to the algorithm.
When the algorithm API layer uses the driver, it is no longer
bound to the fixed device driver, but dynamically obtained
and stored according to the algorithm query to use.
Update the driver and API layer of the zip module, keep the
function of the init interface unchanged, update the implementation
of the init2 interface and match the dynamic loading function.
> Add dynamic driver loading function

- drv/hisi_sec.c
- include/drv/wd_aead_drv.h
- include/drv/wd_cipher_drv.h
- include/drv/wd_digest_drv.h
- include/wd_cipher.h
- libwd_crypto.map
- wd_cipher.c
In order to simplify the calling logic of uadk, a new init2 interface
is added to the cipher algorithm class, which includes hardware device
resource initialization and scheduler initialization.
> uadk: update cipher init2 interface

- wd_comp.c
In the current version, when the resource of comp is destroyed, there is no effective blanking operation for setting's priv
therefore, this operation needs to be performed directly on the priv of the setting.
> uadk/comp: fix duplicate release of comp

- uadk_tool/Makefile.am
Search dynamic lib sequence
1. DT_RPATH: -Wl,-rpath,'/usr/local/lib'
2. LD_LIBRARY_PATH
3. DT_RUNPATH: -Wl,-rpath,'/usr/local/lib',--enable-new-dtags
If using DT_RPATH, LD_LIBRARY_PATH will be ignored, and uadk_tool will always search libwd.so under /usr/local/lib, except rm it.
If remove DT_RPATH, LD_LIBRARY_PATH has to be provided even when library is under /usr/local/lib
So use DT_RUNPATH, if LD_LIBRARY_PATH is provide, use it If LD_LIBRARY_PATH is not provide, use the default DT_RUNPAT.
Example
./test.sh
wd_get_lib_file_path file_path=/usr/local/lib/libwd_crypto.so.2
LD_LIBRARY_PATH=/tmp/build/lib ./test.sh
wd_get_lib_file_path file_path=/tmp/build/lib/libwd_crypto.so.2
> uadk_tool: use DT_RUNPATH instead of DT_RPATH

- include/wd_cipher.h
The wd_cipher_init2 should define as wd_cipher_init2_
> uadk/cipher: fix wd_cipher_init2 typo

- drv/hisi_comp.c
- drv/hisi_hpre.c
- drv/hisi_sec.c
- include/wd_alg.h
- include/wd_util.h
- wd_aead.c
- wd_cipher.c
- wd_comp.c
- wd_dh.c
- wd_digest.c
- wd_ecc.c
- wd_rsa.c
- wd_util.c
A driver should alloc and free resources by himself instead of the caller, considering multi-driver exists, the caller can not hold ctx for all drivers, so drv.init malloc private ctx and drv.exit free.
Add driver as para of alg ops, not only for getting private ctx, but easier for multi-driver support.
> uadk: driver alloc and free resources by itself

- include/wd_util.h
- v1/wd_cipher.c
- wd_aead.c
- wd_cipher.c
- wd_comp.c
- wd_dh.c
- wd_digest.c
- wd_ecc.c
- wd_rsa.c
- wd_util.c
The first patch adds init wait timeout judgment to prevent deadlocks
when making loopback calls from the same thread.
The second and third patches add a key length validity check before
calculating the actual key length of the algorithm in xts mode. Because
if the key length is odd, it will result in incorrect calculation results.
> This patchset fixes some issues of the uadk.

- Makefile.am
- wd_util.c
Solving the problem of traversing the entire library directory to load alg drv lib may result in unexpected results by specifying the loading directory 'uadk'.
> uadk: support loading alg lib from the specified directory

- include/wd_zlibwrapper.h
- v1/drv/hisi_zip_udrv.c
- wd_zlibwrapper.c
Fix two bugs.
1. Since the wd_alg_try_init change the return value, wd_zlibwrapper shoud add the return value check.
2. Support sqe_priv ops for hisilicon comp BD v3.
> Upstream :fix two zip module's software issues

- drv/hisi_sec.c
- v1/drv/hisi_sec_udrv.c
- v1/wd_digest.c
Optimize the zero byte packet checking in bd2 and
add the zero byte packet checking in bd3.
Hardware v2: long hash mode does not support 0 byte packet in the
frist and middle bd. Block hash mode does not support 0 byte packet.
Hardware v3: long hash mode does not support 0 byte packet in the
frist and middle bd. But, block hash mode do support 0 byte packet.
> uadk/digest: optimize the zero byte packet checking for   hash

- drv/hisi_qm_udrv.c
- include/wd_comp.h
- v1/drv/hisi_zip_udrv.c
- v1/wd_comp.c
- wd.c
- wd_alg.c
- wd_comp.c
- wd_util.c
- wd_zlibwrapper.c
1. Fix missed unmap operations.
2. Fix wrong sizes on unmap.
3. Fix unsymmetric resource processing process.
4. Add parameters check.
5. Clean up.
6-7. Fix error branch in wd_init_ctx_set.
8. Fix fscanf infinite loop.
9. Add req.status check in wd_zlibwrapper.
10. Fix sgl copy error.
> Upstream some bugfixes and cleanups

- test/sanity_test.sh
Since it's triggered a bug in hw_ifl_perf() in block mode, disable it temporarily.
> test: disable inflate test for performance temporary

- Makefile.am
- configure.ac
Add PIE、PIC、BIND_NOW、SP、NO Rpath/RunPath、FS、Ftrapv and Strip compilation option.
> uadk: add secure compilation option

- test/wd_mempool_test.c
- uadk_tool/benchmark/hpre_uadk_benchmark.c
- uadk_tool/benchmark/hpre_wd_benchmark.c
- uadk_tool/benchmark/sec_uadk_benchmark.c
- uadk_tool/benchmark/sec_wd_benchmark.c
- uadk_tool/benchmark/uadk_benchmark.c
- uadk_tool/benchmark/uadk_benchmark.h
- uadk_tool/test/test_sec.c
- v1/test/hisi_zip_test_sgl/zip_alg_sgl.h
- v1/test/test_mm/test_wd_mem.c
- v1/test/test_mm/test_wd_mem.h
- v1/wd_rsa.c
- wd_mempool.c
- wd_rsa.c
./cleanup.sh
./autogen.sh
./configure CC=clang
make
build error logs like:
wd_rsa.c:48:24: error: field 'pkey1' with variable sized type 'struct wd_rsa_prikey1' not at the end of a struct or class is a GNU extension [-Werror,-Wgnu-variable-sized-type-not-at-end] v1/wd_rsa.c:108:29: error: field 'pkey1' with variable sized type 'struct wcrypto_rsa_prikey1' not at the end of a struct or class is a GNU extension [-Werror,-Wgnu-variable-sized-type-not-at-end] clang-12: error: -Wl,-z,now: 'linker' input unused [-Werror,-Wunused-command-line-argument] clang-12: error: -Wl,-s: 'linker' input unused [-Werror,-Wunused-command-line-argument] clang-12: error: -Wl,-z,now: 'linker' input unused [-Werror,-Wunused-command-line-argument] clang-12: error: -Wl,-s: 'linker' input unused …
> uadk: fix build errors with clang

- drv/hisi_comp.c
- drv/hisi_hpre.c
- drv/hisi_sec.c
The drivers initialization function use 'drv.priv' to forbid reinit. But if the child process is forked after the parent process has initialized, it can't work due to the drivers go to wrong branch on initialization.
And the algorithms initialization function is already protected against re-entry. So it is unnecessary to check 'drv.priv' in driver.
> uadk: drv/hisi - fix failed to init drv after fork

- Makefile.am
- drv/isa_ce_sm4.c
- drv/isa_ce_sm4.h
- drv/isa_ce_sm4_armv8.S
- v1/wd.c
- v1/wd_rng.c
- wd_cipher.c
Qi Tao (1):
cipher: add support for SM4(ECB) algorithm in CE instruction
Wenkai Lin (1):
cipher: add support for SM4 CBC and CTR modes in CE instruction
Yang Shen (1):
uadk/cipher: isa_ce - support SM4 cbc_cts mode
Yuzeng Zhuang (1):
cipher: add support for SM4 CFB and XTS modes in CE instruction
Makefile.am            |    5 +-
drv/isa_ce_sm4.c       |  472 +++++++++
drv/isa_ce_sm4.h       |   62 ++
drv/isa_ce_sm4_armv8.S | 2296 ++++++++++++++++++++++++++++++++++++++++
wd_cipher.c            |    4 +-
5 files changed, 2835 insertions(+), 4 deletions(-)
create mode 100644 drv/isa_ce_sm4.c
create mode 100644 drv/isa_ce_sm4.h
create mode 100644 drv/isa_ce_sm4_armv8.S
> Add support for SM4 algorithm in CE instruction

- uadk_tool/benchmark/sec_soft_benchmark.c
When openssl is with 'no-sm4', which cause macro 'OPENSSL_NO_SM4' is defined. 
So sm4 benchmark should check the macro too, otherwise build would be failed.
> uadk_tool/benchmark: skip sm4 benchmark if openssl with 'no-sm4'

- drv/hash_mb/hash_mb.c
- drv/isa_ce_sm3.c
- drv/isa_ce_sm4.c
- uadk_tool/benchmark/hpre_uadk_benchmark.c
- uadk_tool/benchmark/hpre_wd_benchmark.c
- uadk_tool/benchmark/sec_soft_benchmark.c
- uadk_tool/benchmark/sec_uadk_benchmark.c
- uadk_tool/benchmark/sec_wd_benchmark.c
- uadk_tool/benchmark/trng_wd_benchmark.c
- uadk_tool/benchmark/uadk_benchmark.c
- uadk_tool/benchmark/uadk_benchmark.h
- uadk_tool/benchmark/zip_uadk_benchmark.c
- uadk_tool/benchmark/zip_wd_benchmark.c
- v1/drv/hisi_hpre_udrv.c
- v1/drv/hisi_qm_udrv.c
- v1/drv/hisi_qm_udrv.h
- v1/drv/hisi_rng_udrv.c
- v1/drv/hisi_rng_udrv.h
- v1/drv/hisi_zip_udrv.c
- v1/wd_util.c
- wd_mempool.c
- wd_util.c
Longfang Liu (2):
uadk_tools: add segfault locating function
uadk: bugfix CE driver initialization problem
Wenkai Lin (5):
uadk/v1: fix for atomic memory order
uadk: replace wd_lock to pthread_spinlock
uadk/v1: fix for wd_lock implementation
uadk: fix for env uninit segment fault
uadk/v1: replace wd_spinlock to pthread_spin_lock
Yang Shen (1):
uadk/v1/drv: hisi_zip_udrv - fix the wrong literal buffer size
Zhiqi Song (1):
uadk/v1/hpre: remove redundant comments
drv/hash_mb/hash_mb.c                     |  4 ++
drv/isa_ce_sm3.c                          |  6 +-
drv/isa_ce_sm4.c                          |  4 ++
uadk_tool/benchmark/hpre_uadk_benchmark.c |  1 +
uadk_tool/benchmark/hpre_wd_benchmark.c   |  1 +
uadk_tool/benchmark/sec_soft_benchmark.c  |  1 + …
> bugfix for uadk

- drv/hisi_sec.c
- include/wd_util.h
- v1/drv/hisi_sec_udrv.c
- v1/libwd.map
- v1/wd.c
- wd_aead.c
- wd_cipher.c
- wd_digest.c
- wd_util.c
Weili Qian (3):
uadk: modify address check
uadk: check calloc return value
drv/hisi_sec: modify minor errors in hisi_sec.c
Wenkai Lin (3):
uadk/v1: fix for sec_dump_bd
uadk/v1: fix for wd_recv_sync print
uadk/v1: update the symbol table for libraries
drv/hisi_sec.c         | 59 ++++++++++++++++++++++++++----------------
include/wd_util.h      |  2 +-
v1/drv/hisi_sec_udrv.c | 13 ++++------
v1/libwd.map           |  1 +
v1/wd.c                | 11 +++++---
wd_aead.c              | 19 +++++++-------
wd_cipher.c            | 14 +++++-----
wd_digest.c            | 18 ++++++++-----
wd_util.c              | 14 ++++++----
9 files changed, 88 insertions(+), 63 deletions(-)
> uadk bugfix and cleancode

- drv/isa_ce_sm3.c
- drv/isa_ce_sm4.c
CE driver of sm4 should alloc and free private ctx by himself. The cleancode issue of sm3 CE driver is also solved.
> uadk/isa-ce: fix sm4 CE driver initialization error

- drv/hisi_comp.c
- drv/hisi_hpre.c
- v1/drv/hisi_zip_udrv.c
- wd.c
- wd_aead.c
- wd_agg.c
- wd_cipher.c
- wd_comp.c
- wd_dh.c
- wd_digest.c
- wd_ecc.c
- wd_rsa.c
- wd_util.c
- wd_zlibwrapper.c
Qi Tao (3):
acc/uadk: fix double-free error
acc/uadk: fix queue configuration parameter error.
uadk: fix the null pointer check error
drv/hisi_comp.c        | 3 ++-
drv/hisi_hpre.c        | 3 ++-
v1/drv/hisi_zip_udrv.c | 3 ++-
wd.c                   | 3 ---
wd_aead.c              | 2 +-
wd_agg.c               | 4 ++--
wd_cipher.c            | 4 ++--
wd_comp.c              | 2 +-
wd_dh.c                | 6 ++++--
wd_digest.c            | 4 ++--
wd_ecc.c               | 6 ++++--
wd_rsa.c               | 6 ++++--
wd_util.c              | 4 ++++
wd_zlibwrapper.c       | 8 ++++----
14 files changed, 34 insertions(+), 24 deletions(-)
> uadk bugfix

- drv/hisi_sec.c
- include/drv/wd_agg_drv.h
- include/wd_agg.h
- include/wd_dae.h
- wd_cipher.c
Qi Tao (2):
uadk: fix for hashagg include files
uadk: fix code compatibility issue
drv/hisi_sec.c           | 4 ++--
include/drv/wd_agg_drv.h | 1 +
include/wd_agg.h         | 1 -
include/wd_dae.h         | 1 +
wd_cipher.c              | 6 ------
5 files changed, 4 insertions(+), 9 deletions(-)
> uadk: fix code compatibility issue

- uadk_tool/Makefile.am
- uadk_tool/test/uadk_test.c
On OpenSSL 3.0 comp_lib build error
test/comp_lib.c: In function 'calculate_md5':
test/comp_lib.c:258:9: error: 'MD5_Init' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
258 |         MD5_Init(&md5->md5_ctx);
|         ^~~~~~~~
In file included from test/comp_lib.h:11,
from test/comp_lib.c:14:
/usr/local/include/openssl/md5.h:49:27: note: declared here
49 | OSSL_DEPRECATEDIN_3_0 int MD5_Init(MD5_CTX *c);
|                           ^~~~~~~~
test/comp_lib.c:259:9: error: 'MD5_Update' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
259 |         MD5_Update(&md5->md5_ctx, buf, len);
|         ^~~~~~~~~~
/usr/local/include/openssl/md5.h:50:27: note: declared here
50 | OSSL_DEPRECATEDIN_3_0 int MD5_Update(MD5_CTX *c, const void *data, size_t len);
| …
> uadk_tool: comp_lib build error on OpenSSL 3.0

- test/sanity_test.sh
When ci fails, it is very difficult to reproduce.
Add set -x in build script, to make it is easier to find which cmd fails.
> sanity_test: add set -x to print cmd

- v1/wd_digest.c
- v1/wd_digest.h
In common digest stream mode, io_bytes and iv_bytes need to be set to 0 when the final bd is calculated. Therefore, in the appending tag scenario, need to restore the values of io_bytes and iv_bytes to the values before they are set to 0.
Therefore, the hardware can compute the overall hash value of the appending packet and the previously calculated packet, and reduce the repeated calculation.
> uadk: support appending tag for digest stream model

- drv/hisi_sec.c
- drv/isa_ce_sm3.c
- uadk_tool/benchmark/uadk_benchmark.c
- uadk_tool/benchmark/uadk_benchmark.h
- uadk_tool/uadk_tool.c
- v1/drv/hisi_sec_udrv.c
- v1/wd_aead.c
- v1/wd_cipher.c
- v1/wd_digest.c
- wd_aead.c
- wd_digest.c
Junchong Pan (1):
uadk_tool: print help when empty parameters
Wenkai Lin (7):
uadk: fix for aead authsize check
uadk: fix for aead auth key length
uadk: fix for digest auth key length
uadk: fix for ce key_len check
uadk: fix for key address check
uadk: fix for v1 aead authsize check
uadk: fix for aead cbc mode authsize
drv/hisi_sec.c                       | 40 +++++++++++++-------------
drv/isa_ce_sm3.c                     |  5 ----
uadk_tool/benchmark/uadk_benchmark.c |  6 ++--
uadk_tool/benchmark/uadk_benchmark.h |  1 +
uadk_tool/uadk_tool.c                | 10 ++++++-
v1/drv/hisi_sec_udrv.c               | 18 ++----------
v1/wd_aead.c                         | 41 ++++++++++++++++++++-------
v1/wd_cipher.c                       |  2 +-
v1/wd_digest.c                       | 42 …
> uadk: some bugfix

- wd_util.c
sync from develop to master
// this patch is required
3f17c6f uadk: set default value cparams->bmp for init2
// this patch is optional, ignore since conflict in wd_zlibwrapper.c
02b222c uadk_tool: using default cparams->bmp
> uadk: set default value cparams->bmp for init2

- wd_zlibwrapper.c
In the destructor, it need to check whether zlibwrapper has been initialized, otherwise it will cause double free.
> uadk: fix a double free issue in zlibwrapper

- uadk_tool/dfx/uadk_dfx.c
Usage of __DATE__ and __TIME__ cause "build not reproducible" warnings on Debian (-Wdate-time) when building with dpkg-buildpackage, and since -Werror is set it breaks the build.  Just remove the functionality; it's not important enough to be worth it.
> Remove uadk_tool dfx --date; __DATE__ and __TIME__ cause problems

- drv/hisi_comp.c
- drv/hisi_comp_huf.c
- include/wd_comp.h
- uadk_tool/benchmark/uadk_benchmark.c
- uadk_tool/benchmark/uadk_benchmark.h
- uadk_tool/benchmark/zip_uadk_benchmark.c
- v1/drv/hisi_zip_huf.c
- v1/drv/hisi_zip_udrv.c
- wd_comp.c
- wd_util.c
Chenghai Huang (7):
uadk: fix definition coding standard issues
uadk: add or remove some store buf condition judgments
uadk: add new alg called lz77_only
uadk: remove redundant checks on bit read results
uadk_tool: modify unrecv num in async benchmark test
uadk_tool: add lz77_only alg in zip benchmark test
uadk_tool: add lz4 alg in zip benchmark test
Qinxin Xia (3):
uadk: hisi_comp - abstract get sgl function and general deflate
functions
uadk: hisi_comp - support the new algorithm 'lz4'
uadk: wd_comp - support the new algorithm 'lz4'
> uadk: support lz77_only and  lz4
