test/hisi_sec_test/test_hisi_sec.c
update sec digest sync/async test tools code to
support perf test.
=> test: sec: modify sec perf test tools code

test/sched_sample.c
=> Add schdule cache feature.

drv/hisi_hpre.c, include/drv/wd_dh_drv.h, include/hisi_qm_udrv.h, include/wd_dh.h, include/wd_rsa.h, test/hisi_hpre_test/test_hisi_hpre.c, test/hisi_sec_test/test_hisi_sec.c, wd_dh.c, wd_rsa.c
=> hpre: fix coding style

INSTALL, README
Add instructions on building UADK and running test cases in INSTALL document.
=> docs: append INSTALL doc

test/sanity_test.sh
=> test: Add sanity test script

test/hisi_hpre_test/hpre_test_sample.h, test/hisi_hpre_test/test_hisi_hpre.c, test/hisi_hpre_test/test_hisi_hpre.h, test/hisi_sec_test/test_hisi_sec.c, test/hisi_sec_test/test_hisi_sec.h
=> test: Modify to use Apache license in SPDX way

Makefile.am, drv/hisi_sec.c, include/drv/wd_aead_drv.h, include/wd_aead.h, wd_aead.c
1.Added AEAD APIs for uadk
2.Added AEAD user mode driver for uadk
3.Fixed some coding styles
=> wd/sec: add AEAD algorithm driver for uadk

include/wd_aead.h
modify AEAD APIs head file comment
=> wd/sec: modify AEAD comment

wd_comp.c
Signed-off-by: Hao Fang <fanghao11@huawei.com>
=> wd: comp: Fix stream mode crc32 update

drv/hisi_sec.c, wd_aead.c
Added the AEAD aiv addr for the async mode
=> wd:aead: modify AEAD async driver code

wd_comp.c
1. Merge duplicated code. Most code could be shared between compression
and decompression.
2. Update avail_out for each transition.
3. The length of each line should be limited in 80 characters.
=> wd_comp: optimize on wd_do_comp_sync2()

test/hisi_zip_test/test_lib.h, wd_comp.c
1.fix stream avail out zero.
2.fix -h print.
3.add ctx mode verify.
Signed-off-by: Hao Fang <fanghao11@huawei.com>
=> wd: comp: fix stream availout zero issue

drv/hisi_sec.c, include/wd_alg_common.h, test/hisi_sec_test/test_hisi_sec.c, wd_aead.c, wd_cipher.c, wd_comp.c, wd_dh.c, wd_digest.c, wd_rsa.c, wd_util.c
1.add poll parameter check
2.update SEC algorithm specifications
3.add ctx mode check for SEC
4.modify API uninit interface
=> wd: fixes some bugs for SEC

include/wd.h, test/hisi_hpre_test/Makefile.am, test/hisi_sec_test/Makefile.am, test/hisi_zip_test/Makefile.am, wd.c
Clean unused field in struct uacce_dev. And add more comments.
=> wd: clean unused fields

INSTALL, Makefile, drv/Makefile, include/hisi_qm_udrv.h, include/wd.h, include/wd_aead.h, include/wd_cipher.h, include/wd_comp.h, include/wd_dh.h, include/wd_digest.h, include/wd_rsa.h, test/Makefile, test/hisi_hpre_test/Makefile, test/hisi_sec_test/Makefile, test/hisi_zip_test/Makefile, wd_comp.c, wd_dh.c, wd_rsa.c
Use manual makefile as a workaround.
=> Manual makefile

INSTALL
=> docs/INSTALL: update cipher/digest test command

drv/hisi_sec.c
1. update IV data after a task.
2. bugfix the aead MAC BD parameter
=> wd/sec: fix cipher and aead bugs

wd_aead.c, wd_cipher.c, wd_digest.c
1. update poll_policy interface parameter
2. fix some cleancode
=> wd/sec: update cipher/digest/aead driver

test/hisi_sec_test/test_hisi_sec.c
Using lock to protect wd_do_cipher_sync/async is no need. However, schedule
context should be protected by user.
This patch removes lock outside of wd_do_cipher_sync/async, and adds lock in
schedule. After this patch, perf of sync multiple threads/ctxs is improved,
former bad perf is the problem of sec test app.
Perf at this point is:
numactl --cpubind 1 --membind 1  test_hisi_sec --perf --sync --pktlen 1024 \
--block 1024 --blknum 100000 --times 100000 --multi 8 --ctxnum 8
time_used:340679 us, send task num:800000
Sync mode avg Pro-50922, thread_id-50922, speed:2348251.500000 ops, Perf: 2348251 KB/s
numactl --cpubind 1 --membind 1  test_hisi_sec --perf --async --pktlen 1024 \
--block 1024 --blknum 100000 --times 100000 --multi 8 --ctxnum 8
time_used:474985 us, send task num:800000
Async …
=> test: sec: Remove sending lock in test app

test/hisi_sec_test/test_hisi_sec.c
bugfix SEC test tools of AES-XTS and SM4-XTS test error
=> wd/sec: modify SEC test tools

drv/hisi_qm_udrv.c, drv/hisi_sec.c, include/hisi_qm_udrv.h
Add new BD type3 algorithms for SEC driver
and solved the driver compatibility issues.
=> wd/sec: add new algorithms for Kunpeng930

drv/hisi_qm_udrv.c
Add the resource release in alloc qp.
=> drv: qm: Fixed bugs of sgl pool manage in qm

drv/hisi_qm_udrv.c
Sgl pool support multithreading.
=> drv: qm: Add lock to sgl pool

drv/hisi_sec.c
The para shoule use '|=',otherwise it will coverage.
=> drv: sec: Fixed bug in filling bd

drv/hisi_qm_udrv.c, drv/hisi_sec.c
=> drv: qm: Fixed bug in sgl

drv/hisi_sec.c
=> wd/sec: modify sec driver for update iv

Makefile.am
=> version: update to 2.1.0

drv/hisi_qm_udrv.c, include/hisi_qm_udrv.h
add version id.
Signed-off-by: Hui tang <tanghui@8237897913@qq.com>
=> wd/qm: adapt v3 version

drv/hisi_qm_udrv.c
Signed-off-by: Hui tang <tanghui@8237897913@qq.com>
=> WD/qm：Fix hw_type update

Makefile.am
=> version: update to 2.1.2

drv/hisi_qm_udrv.c, test/hisi_sec_test/test_hisi_sec.c
When one hw sgl is not enough to hold the user wd sgl chains, the
qm will create the multi hw sgl chanin automatically.
=> drv: qm: Support the multiple sgl chain

Makefile.am
=> version: update to 2.1.3

drv/hisi_qm_udrv.c
The max buff size in one sge is 8M, we should
check the size before user buff to hw sgl. If
the buff is bigger than 8M, qm will return a
NULL point to alg driver.
=> drv: qm: Add the hw specification in sgl pool

Makefile.am
=> version: update to 2.1.4

Makefile.am
=> version: update to 2.1.5

drv/hisi_hpre.c, include/wd_ecc.h, wd_ecc.c
Signed-off-by: wenkai lin <linwenkai755@qq.com>
=> Add ECDSA alg support

drv/hisi_comp.c, include/drv/wd_comp_drv.h, include/wd_comp.h, test/hisi_zip_test/sva_file_test.c, test/hisi_zip_test/test_lib.c, test/hisi_zip_test/test_lib.h, wd_comp.c
support the algorithm deflate in wd_comp.c and drv/hisi_comp.c
=> support deflate

Makefile.am
=> version: update to 2.1.6

Makefile.am
=> version: update to 2.1.7

Makefile.am
=> version: update to 2.1.8

drv/hisi_hpre.c, include/drv/wd_ecc_drv.h, include/wd_ecc.h, test/hisi_hpre_test/test_hisi_hpre.c, wd_ecc.c
Signed-off-by: Yu Meng <yumeng18@huawei.com>
=> wd: Modify function name used in ECDH and X25519/X448

Makefile.am
=> version: update to 2.2.0

drv/hisi_qm_udrv.c, drv/hisi_sec.c, test/hisi_sec_test/test_hisi_sec.c
=> drv: sec: Fixed the code style

Makefile.am
=> version: update to 2.2.1

Makefile.am
=> version: update to 2.2.2

drv/hisi_hpre.c, wd_ecc.c
Signed-off-by: TangHui <823787913@qq.com>
=> wd/hpre:Fix clean code

Makefile.am
=> version: update to 2.2.3

Makefile.am
=> version: update to 2.2.4

Makefile.am
=> version: update to 2.2.5

drv/hisi_sec.c
bugfix the Digest output mac not match protocol data
Signed-off-by: TangHui <823787913@qq.com>
=> wd/sec: modify digest algorithms parameter

Makefile.am
=> version: update to 2.2.6

drv/hisi_sec.c
Signed-off-by: TangHui <823787913@qq.com>
=> wd/sec: modify cipher 3des algorithms parameter

Makefile.am
=> version: update to 2.2.7

Makefile.am
=> version: update to 2.2.8

Makefile.am
=> version: update to 2.2.9

wd_aead.c, wd_cipher.c, wd_digest.c
set the BD reception state to user side normally
=> wd/sec: modify BD return state

Makefile.am
=> version: update to 2.2.10

wd_ecc.c
1. memory leak;
2. SM2 data len is always 32;
Signed-off-by: Yu Meng <yumeng18@huawei.com>
=> UADK/HPRE - ECC: fix some bug in ecc

drv/hisi_qm_udrv.c, include/wd.h, include/wd_alg_common.h
Signed-off-by: wenkai lin <linwenkai755@qq.com>
=> wd - some code clean for wd and qm

test/hisi_sec_test/test_hisi_sec.c
Two kinds of thread data are used in sec_sva_test(),
sva_sync_create_threads() and sva_async_create_threads().
Fix to only use the thread data defined in sec_sva_test(). Avoid to use
the global thread data in both sva_sync_create_threads() and
sync_async_create_threads().
=> test: sec: clean thread data in sec_sva_test()

Makefile.am
=> version: update to 2.2.11

drv/hisi_hpre.c, drv/hisi_qm_udrv.c, include/drv/wd_ecc_drv.h, include/wd_dh.h, wd_dh.c, wd_ecc.c, wd_rsa.c, wd_util.c
wd/rsa - modyfy rsa error found by ut
wd/hpre - clean code
=> wd clean code

Makefile.am
=> version: update to 2.2.12

drv/hisi_hpre.c, drv/hisi_qm_udrv.c, wd.c, wd_dh.c
=> Code clean  for qm and wd

Makefile.am
=> version: update to 2.2.13

drv/hisi_sec.c
Add icv check for aead alg when doing decryption
=> wd/sec: add icv check for aead algorithm

Makefile.am
=> version: update to 2.2.14

drv/hisi_qm_udrv.c
stop queue if it already start and clean hisi_qm_create_sgl.
=> qm optimize and code clean

Makefile.am
=> version: update to 2.2.15

test/Makefile.am, test/wd_mempool_test.c
Signed-off by: Sihang Chen <chensihang1@hisilicon.com>
Signed-off by: Zhenkun Mi <mi_zhenkun@163.com>
=> wd: Add a memory pool test

Makefile.am
=> version: update to 2.2.16

drv/hisi_qm_udrv.c, drv/hisi_sec.c, include/drv/wd_aead_drv.h, include/hisi_qm_udrv.h, include/wd_util.h, test/hisi_sec_test/test_hisi_sec.c, wd_aead.c, wd_cipher.c, wd_digest.c, wd_util.c
1.If send failed need release sgl handle
2.support sgl copy funtion.
3.check src/dst datalist with req bytes.
=> Some sgl bugfix and optimize from inner version

Makefile.am
=> version: update to 2.2.17

wd_cipher.c, wd_digest.c
nginx may fork worker processes after master process
So remove the limitaiton here to make fork possible
=> wd: sec: remove ctx_num limitation

Makefile.am
=> version: update to 2.2.18

Makefile.am
=> version: update to 2.3.0

include/drv/wd_dh_drv.h, include/drv/wd_ecc_drv.h, include/drv/wd_rsa_drv.h, wd_dh.c, wd_ecc.c, wd_rsa.c
Fix dynamic build for rsa and dh algorithm.
Signed-off-by: Hui Tang <823787913@qq.com>
=> wd/hpre - fix dynamic build

Makefile.am
=> version: update to 2.3.1

Makefile.am
=> wd: version: update to 2.3.2

Makefile.am
=> version: update to 2.3.3

Makefile.am
=> version: update to 2.3.4

drv/hisi_hpre.c, test/wd_mempool_test.c, wd.c
Signed-off-by: linwenkai <linwenkai6@hisilicon.com>
=> wd: fix uadk compile compat problem

v1/test/hisi_sec_test/test_hisi_sec.c, v1/test/hisi_sec_test/test_hisi_sec.h
modify the Warpdrive sec test code
1. add default test case.
2. modify the test parameters.
=> wd v1/sec test: modify the no-sva test code

drv/hisi_sec.c, v1/drv/hisi_sec_udrv.h
Modify the SEC sqe type3 according to the new FS.
=> wd: modify the SEC sqe type3

test/hisi_sec_test/test_hisi_sec.c
Signed-off-by: linwenkai <linwenkai6@hisilicon.com>
=> test/sec : add sgl format test for aead

drv/hisi_qm_udrv.c, include/hisi_qm_udrv.h, include/wd.h
Doorbell function should not use magic number,
and move comments to better place.
Signed-off-by: linwenkai <linwenkai6@hisilicon.com>
=> hisi: qm: clean code for qm

Makefile.am
=> version: update to 2.3.6

docs/maintenance.md
=> doc: add maintainer

v1/wd_aead.c, v1/wd_cipher.c, v1/wd_digest.c, wd_aead.c
1.Remove the unused modes in the AEAD algorithm
2.Update the return value of the encryption and decryption
operation interface.
=> wd/sec/v1: update interface return value

drv/hisi_hpre.c, drv/hisi_qm_udrv.c, include/uacce.h, wd.c, wd_aead.c, wd_cipher.c, wd_comp.c, wd_digest.c, wd_mempool.c
1.uadk mempool remove pin
2.uadk mempool alg optimize
3.uadk wd_ctx_wait apply to sync mode
4.fix kora warning
=> Sync from inner develop

Makefile.am
=> version: update to 2.3.7

wd_comp.c
When a large buffer is used to compress by wd_do_comp_sync2(), the
condition logic doesn't work. Fix it in wd_do_comp_sync2().
=> wd: comp: fix logic in wd_do_comp_sync2()

Makefile.am
=> version: update to 2.3.8

drv/hisi_hpre.c, include/wd.h, include/wd_comp.h, include/wd_ecc.h, include/wd_rsa.h, v1/drv/hisi_qm_udrv.c, v1/wd.h, v1/wd_cipher.c, v1/wd_comp.c, v1/wd_rng.c, wd.c
1.use strcmp to check alg name
2.remove extra extern in head file
3.fix code review problem
=> uadk code clean and bugfix

test/hisi_zip_test/test_lib.c, test/hisi_zip_test/testsuit.c
=> test/zip: fix build error with gcc version

v1/drv/hisi_qm_udrv.c, v1/wd_aead.c, v1/wd_cipher.c, v1/wd_digest.c, wd_aead.c, wd_cipher.c, wd_digest.c
1. v1/wd:sec: modify sec burst send
2. wd/sec: modify some codint styles
=> v1/wd:sec: modify sec burst send and coding styles

AUTHORS
Signed-off-by: Hao Fang <haofangcas@163.com>
=> wd: remove the authors file

include/wd_dh.h, include/wd_ecc.h, include/wd_rsa.h, test/hisi_hpre_test/test_hisi_hpre.c, wd_aead.c, wd_cipher.c, wd_comp.c, wd_dh.c, wd_digest.c, wd_ecc.c, wd_rsa.c, wd_util.c
1.Add hpre alg environment variable api
2.If system has no numa node ,return fail
3.default value is changed to the minimum value
=> wd: env: support rsa, dh and ecc

Makefile.am
=> version: update to 2.3.10

wd.c
Sometimes, a hardware accelerator will report some error frequently since it
goes bad. To make sure up layer task running normally, we have to isolate it
to avoid up layer get queues from it.
=> uadk: wd - adding hardware error isolation of ACC

wd_util.c
First,check whether there is a ctx table,
if there is no ctx table,split ctxs into
two types.If there is ctx table,there're
four types ctx.At last we need to check
whether if ctx num is zero.
=> wd env bufgfix

docs/maintenance.md
Update maintainer in document.
=> doc: update maintainer

v1/wd_digest.c
Add in bytes aligned size checking for stream mode. Others it will
cause hardware error.
=> wd/digest : add input bytes aligned size for stream mode

docs/wd_environment_variable, drv/hisi_comp.c, drv/hisi_qm_udrv.c, include/wd.h, include/wd_aead.h, include/wd_alg_common.h, include/wd_cipher.h, include/wd_comp.h, include/wd_dh.h, include/wd_digest.h, include/wd_ecc.h, include/wd_rsa.h, include/wd_sched.h, include/wd_util.h, test/hisi_zip_test/testsuit.c, wd.c, wd_aead.c, wd_cipher.c, wd_comp.c, wd_dh.c, wd_digest.c, wd_ecc.c, wd_mempool.c, wd_rsa.c, wd_util.c
use WD_<alg>_CTX_NUM to define alg ctx number.
for zip,use by WD_COMP_CTX_NUM=""sync-comp:1@0,async-decomp:1@0"
for sec and hpre,use by WD_COMP_CTX_NUM=""sync:1@0,async:1@0"
=> Optimize for wd env and code clean

INSTALL, test/hisi_hpre_test/Makefile.am, test/hisi_zip_test/Makefile.am, v1/test/hisi_zip_test/Makefile.am, v1/test/hisi_zip_test_sgl/Makefile.am, v1/test/test_mm/Makefile.am
Add instructions on how to build UADK by cross compiler. And update the
related Makefile.
=> wd: make uadk built by cross compiler

Makefile.am
=> version: update to 2.3.12

Makefile.am
=> version: update to 2.3.13

Makefile.am
=> version: update to 2.3.14

drv/hisi_qm_udrv.c, include/wd.h
This reverts commit e69a0698235060e9aa169c24128a98c3a439b2be.
=> Revert "wd: bugfix IO memory synchronization"

Makefile.am
=> version: update to 2.3.15

Makefile.am, configure.ac, docs/wd_design.md, sample/Makefile.am, sample/uadk_sample.c
Add contents for environment variable into design document.
=> doc: add contents for environment variable

wd_aead.c, wd_cipher.c, wd_comp.c, wd_dh.c, wd_digest.c, wd_ecc.c, wd_rsa.c
Count may be a dirty data, so init it first.
=> wd: alg: fix poll ctx

Makefile.am
=> version: udpate to 2.3.16

drv/hisi_sec.c
1. Modify the code to reduced repetition rate
2. remove some redundant code
=> drv/sec: refactoring the sec user space code

Makefile.am
=> version: update to 2.3.18

drv/hisi_sec.c
1. Optimze the process of the filling the sqe.
2. Modify some comments.
=> drv/sec: optmize the sec user driver

wd_util.c
This patch recover old commit 398da2.
1.reduce the number of queries to find effective
resources from the resource pool by retaining the
index of the effective resource obtained last time.
2.bugfix some coding style.
=> wd: bugfix msg pool idx

Makefile.am
=> version: update to 2.3.19

Makefile.am
=> version: update to 2.3.20

LICENSE
Add an Apache-2.0 license file for uadk.
=> wd: Add license for uadk

Makefile.am
=> version: update to 2.3.21

drv/hisi_sec.c, include/drv/wd_digest_drv.h, test/hisi_sec_test/test_hisi_sec.c, test/hisi_sec_test/test_hisi_sec.h, wd_digest.c
changes v1->v2
fixed the cause of the issue that caused  nginx failed.
=> digest: support the digest stream mode

Makefile.am
=> version: update to 2.3.22

wd_digest.c
1. add some comments for session state.
2. The stream status is set only when the last msg message is
successfully received.
=> digest: some optimizations for digest stream mode

Makefile.am
=> version: update to 2.3.23

Makefile.am
=> version: update to 2.3.24

Makefile.am
=> version: update version to 2.3.25

drv/hisi_sec.c, wd_aead.c, wd_cipher.c, wd_digest.c
Add some dfx information in comments to improves locating
efficiency.
=> hisi-sec: add some dfx information in comments

drv/hisi_sec.c
1. If an error is detected, the system exits rather than
continues. here is fix it.
2. Due to the auth length checking logic same as the api
layer. So this code is reduntant and needs to be deleted.
=> hisi-sec: delete some dummy parameter checking

Makefile.am
=> version: update to 2.3.26

v1/wd_aead.c, v1/wd_cipher.c, v1/wd_digest.c
SEC device processes tasks quickly. If 'usleep' is used to
wait for the hardware to process tasks, CPU scheduling will
reduce performance. Therefore, increase the number of cycles
to replace 'usleep'.
Signed-off-by: Weili Qian <qianweili@huawei.com>
=> uadk/v1: fix the waiting time for receiving task

Makefile.am
=> version: update to 2.3.27

wd_comp.c
Printf should be outside of the lock region.
=> uadk: comp: optimize for spin lock

uadk_tool/sec_uadk_benchmark.c, uadk_tool/sec_wd_benchmark.c, uadk_tool/uadk_benchmark.c
1.bugfix some alg parameter
2.add multi thread for async mode to poll BD
=> uadk/tool: modify uadk_benchmark toos code

uadk_tool/sec_uadk_benchmark.c
modify uadk benchmark thread create warning
=> uadk/tools: modify uadk benchmark clean code

Makefile.am
=> version: update to 2.3.28

include/wd_rsa.h, test/hisi_hpre_test/test_hisi_hpre.c, v1/wd_sgl.c, wd_aead.c, wd_cipher.c, wd_comp.c, wd_dh.c, wd_digest.c, wd_ecc.c, wd_rsa.c
Including:
1. Modify param verification.
2. Fix interface name and log msg.
=> new cleanup and bugfix about uadk

drv/hisi_hpre.c, drv/hisi_qm_udrv.c, v1/drv/hisi_hpre_udrv.c, v1/wd_aead.c, v1/wd_ecc.c, wd.c, wd_ecc.c
Includes:
Fixup about checking device
Cleanup return value and hpre code
=> uadk cleanup and bugfix

Makefile.am
=> version: update to 2.3.29

drv/hisi_sec.c, v1/drv/hisi_sec_udrv.c, wd_digest.c
Kunpeng 920 can supports sm4-ecb by test, and has
been updated the chip fs.
=> drv/sec: support sm4-ecb alg by new fs

Makefile.am
=> version: update to 2.3.30

Makefile.am
=> version: update to 2.3.31

drv/hisi_sec.c
1. Delete some debug code. Debug code is not allowed in the
release version.
2. Fix a code style issue in sec drv exit.
=> drv/sec - modification for clean code

Makefile.am
=> version: update to 2.3.32

Makefile.am
=> version: update to 2.3.33

Makefile.am
=> version: update to 2.3.34

docs/wd_design.md
Remove all end of line space.
Signed-off-by: Yang Shen <shenyang39@huawei.com>
=> uadk/doc - fix text style for wd_design.md

drv/hisi_qm_udrv.c, include/hisi_qm_udrv.h
1. Fix missing destroy pool lock and q_info lock.
2. split send and recv BD q_info lock.
=> fix qm and sgl lock

drv/hisi_hpre.c, drv/hisi_qm_udrv.c, include/drv/wd_dh_drv.h, include/drv/wd_ecc_drv.h, include/drv/wd_rsa_drv.h, include/hisi_qm_udrv.h, wd_dh.c, wd_ecc.c, wd_rsa.c
1. support dump hpre BD information
2. some cleanups
=> support dump hpre BD information

drv/hisi_hpre.c
1. drv/hpre: bugfix about sm2 async parsing error
2. drv/hpre: bugfix async tag of rsa and dh
3. drv/hpre: cleanup ecc sqe parsing process
=> bugfix about sm2 async alg

Makefile.am
=> version: update to 2.3.36

wd_sched.c
In the scenario of setting the default numa parameters, use the numa affinity method to obtain the numa scheduling domain, so as to achieve automatic balanced use of hardware resources.
Signed-off-by: Longfang Liu <liulongfang@huawei.com>
=> uadk/sched: modify the automatic scheduling function

include/drv/wd_cipher_drv.h, include/drv/wd_comp_drv.h, include/drv/wd_digest_drv.h, v1/wd.c, wd.c
1. optimized uacce device query logic
2. update uadk function symbols
=> Optimized device query method

Makefile.am
Update version to 2.3.37
Signed-off-by: Longfang Liu <liulongfang@huawei.com>
=> version: update to 2.3.37

Makefile.am, drv/hisi_qm_udrv.c, include/hisi_qm_udrv.h, v1/drv/hisi_qm_udrv.c, v1/drv/hisi_qm_udrv.h, wd_util.c
1. support getting queue information from acc driver
2. fix spelling mistake
=> support getting queue information from acc driver

Makefile.am, configure.ac
=> version: update to 2.3.38

docs/ReleaseNotes.md, docs/maintenance.md
ReleaseNotes.txt is required for each release.
Basically two releases each year, like in May and November.
=> docs: Add ReleaseNotes for release

Makefile.am, configure.ac, docs/ReleaseNotes.md
=> uadk: release 2.4

drv/hisi_hpre.c, v1/drv/hisi_hpre_udrv.c, v1/wd_ecc.c
1. uadk/v1/ecc: bugfix buffer overwritten of sm2 decryption
2. uadk/ecc: cleanup sm2 dec out code
3. uadk/v1/ecc: bugfix incorrect parameter length
4. uadk/ecc: bugfix incorrect parameter length
=> uadk/ecc: some bugfix about data processing

drv/hisi_hpre.c, include/drv/wd_dh_drv.h, include/drv/wd_ecc_drv.h, include/drv/wd_rsa_drv.h, include/wd_dh.h, include/wd_ecc.h, include/wd_rsa.h, libwd_crypto.map, wd_dh.c, wd_ecc.c, wd_rsa.c
To simplify the calling logic of uadk, a new init2 interface is added to the ecc/rsa/dh algorithm class, which includes hardware device resource initialization and scheduler initialization.
=> uadk: update ecc/rsa/dh function

drv/hisi_hpre.c, drv/hisi_sec.c, wd_dh.c, wd_ecc.c, wd_rsa.c
Misc fixes for hpre driver and asymmetric algorithm API.
=> uadk: some fixes for hpre

drv/hisi_comp.c, drv/hisi_hpre.c, drv/hisi_sec.c, include/wd.h, include/wd_alg.h, wd.c, wd_aead.c, wd_alg.c, wd_cipher.c, wd_digest.c, wd_util.c
According to the needs of device driver registration. Algorithm-driven
priorities and types need to be distinguished.
In addition, the loading function of the device driver has been fixed.
=> uadk: fix some uadk framework issues

libwd_comp.map
=> uadk/comp - export wd_comp_reset_sess

wd_comp.c
Some misc fixes:
1. Add parameters check.
2. Fix some static check.
3. Some typo.
=> uadk/comp - some misc fixes

Makefile.am, configure.ac, docs/ReleaseNotes.md
=> uadk: release 2.5

drv/hisi_qm_udrv.c, v1/drv/hisi_rng_udrv.c, v1/wd_sgl.c
1. Fix local variable type.
2. Fix memory leak in sgl-related interfaces.
=> uadk: fix some issues in uadk

include/wd_alg_common.h, include/wd_util.h, uadk_tool/test/test_sec.c, v1/wd.h, v1/wd_aead.c, v1/wd_cipher.c, v1/wd_comp.c, v1/wd_dh.c, v1/wd_digest.c, v1/wd_ecc.c, v1/wd_rng.c, v1/wd_rsa.c, v1/wd_util.c, v1/wd_util.h, wd_aead.c, wd_cipher.c, wd_comp.c, wd_dh.c, wd_digest.c, wd_ecc.c, wd_rsa.c, wd_util.c, wd_zlibwrapper.c
This patchset adds the message pool depth configuration. Users can input value to initialize the message  pool.
=> uadk: add msg pool depth set

drv/hisi_sec.c, include/wd_cipher.h, v1/drv/hisi_sec_udrv.c, v1/wd_cipher.c, v1/wd_cipher.h, v1/wd_digest.c, v1/wd_digest.h, v1/wd_util.c, wd_alg.c, wd_cipher.c
=> uadk: support new algoritms mode

drv/hisi_hpre.c, drv/hisi_qm_udrv.c, include/wd.h, v1/drv/hisi_hpre_udrv.c, v1/drv/hisi_qm_udrv.c, v1/drv/hisi_rng_udrv.c, v1/drv/hisi_rng_udrv.h
1.fix key transfer error issue
2.remove duplicate header files
3.fix error writing data to uninitialized memory
4.fix resource leak by add qp info clear
5.check queue status before sending doorbells
=> uadk: fix some bug

Makefile.am, configure.ac, docs/ReleaseNotes.md
=> uadk: release 2.6

drv/hisi_sec.c, include/drv/wd_digest_drv.h, include/wd_util.h, wd_digest.c
This patchset is the preparation for the software algorithm. UADK will support the software algorithm later.
=> uadk: prepare for supporting software algorithm

Makefile.am, configure.ac, drv/hisi_sec.c, drv/isa_ce_sm3.c, drv/isa_ce_sm3.h, drv/isa_ce_sm3_armv8.S, include/drv/arm_arch_ce.h, include/drv/wd_digest_drv.h, include/wd_alg.h, include/wd_sched.h, v1/test/hisi_sec_test/test_hisi_sec.c, v1/test/hisi_sec_test_sgl/test_hisi_sec_sgl.c, wd_alg.c, wd_digest.c, wd_sched.c, wd_util.c
Support sync sm3 ce instruction for both block mode and stream mode, 
users can use ce instruction to accelerate sm3 sync task through init2
related functions.
=> uadk/isa-ce: support sm3 ce instruction

wd_aead.c, wd_dh.c, wd_digest.c, wd_ecc.c, wd_rsa.c
Fix wd_rsa_common_uninit re-entry
Fixs: 3fc344a drivers alloc and free resources by themself
=> wd_rsa: fix wd_rsa_common_uninit re-entry

Makefile.am, drv/hash_mb/hash_mb.c, drv/hash_mb/hash_mb.h, drv/hash_mb/md5_mb_asimd_x1.S, drv/hash_mb/md5_mb_asimd_x4.S, drv/hash_mb/md5_mb_sve.S, drv/hash_mb/md5_sve_common.S, drv/hash_mb/sm3_mb_asimd_x1.S, drv/hash_mb/sm3_mb_asimd_x4.S, drv/hash_mb/sm3_mb_sve.S, drv/hash_mb/sm3_sve_common.S, include/wd_alg_common.h, wd_alg.c, wd_sched.c, wd_util.c
Support sm3 and md5 multi-buffer calculation by SVE instructions.
=> uadk:support sm3 and md5 multi-buffer calculation

uadk_tool/Makefile.am, uadk_tool/benchmark/hpre_uadk_benchmark.c, uadk_tool/benchmark/hpre_wd_benchmark.c, uadk_tool/benchmark/sec_uadk_benchmark.c, uadk_tool/benchmark/sec_wd_benchmark.c, uadk_tool/benchmark/trng_wd_benchmark.c, uadk_tool/benchmark/uadk_benchmark.c, uadk_tool/benchmark/uadk_benchmark.h, uadk_tool/benchmark/zip_uadk_benchmark.c, uadk_tool/benchmark/zip_wd_benchmark.c, uadk_tool/test/test_sec.c
Chenghai Huang (3):
uadk_tool: fix the logic for counting retransmissions when busy
uadk/tools - support the nosva test of a specified device
uadk tool: fix the msg pool release bug of async zip benchmark
Longfang Liu (1):
uadk_tool: fix aead performance test issue
Qi Tao (2):
uadk_tool: support sm4 ce benchmark test
uadk_tool: fix queue application failure from multiple devices
Weili Qian (1):
uadk_tool: support sm3/md5 multibuff benchmark test
Yang Shen (1):
uadk/tools - support designated device testing
Zhiqi Song (1):
uadk_tool: support sm3 ce benchmark and function test
uadk_tool/Makefile.am                     |   1 +
uadk_tool/benchmark/hpre_uadk_benchmark.c | 151 ++++++++--
uadk_tool/benchmark/hpre_wd_benchmark.c   |   8 +
uadk_tool/benchmark/sec_uadk_benchmark.c  | 211 …
=> uadk_tool 

drv/hisi_comp.c, drv/hisi_hpre.c, drv/hisi_qm_udrv.c, drv/hisi_sec.c, include/wd_alg.h, include/wd_alg_common.h, uadk_tool/dfx/uadk_dfx.c, v1/drv/hisi_hpre_udrv.c, v1/drv/hisi_sec_udrv.c, wd_aead.c, wd_alg.c, wd_cipher.c, wd_comp.c, wd_dh.c, wd_digest.c, wd_ecc.c, wd_rsa.c, wd_util.c
Longfang Liu (2):
uadk/v1: improve the judgment conditions of tag
uadk: modify uadk static compile
Wenkai Lin (6):
cipher: optimze input lengths check
uadk/v1: fix for sec cipher bd1 ci_gen configuration
uadk: fix for shmget shmflag
sec: optimze for directly assigning values to structures
util: optimize for wd_handle_msg_sync
uadk: drv_hisi - optimize qm recv function
drv/hisi_comp.c          |  8 ++++
drv/hisi_hpre.c          |  9 +++++
drv/hisi_qm_udrv.c       | 45 +++++++++++----------
drv/hisi_sec.c           | 63 ++++++++++++-----------------
include/wd_alg.h         | 26 +++++++++---
include/wd_alg_common.h  | 17 +++++---
uadk_tool/dfx/uadk_dfx.c |  2 +-
v1/drv/hisi_hpre_udrv.c  |  4 +-
v1/drv/hisi_sec_udrv.c   | 12 +++---
wd_aead.c                | 61 +++++++++++++++++++--------- …
=> UADK supports static compilation and code optimization

Makefile.am, configure.ac, docs/ReleaseNotes.md
=> uadk: release 2.7

Makefile.am, drv/hisi_dae.c, drv/hisi_qm_udrv.h, include/drv/wd_agg_drv.h, include/wd_agg.h, include/wd_alg.h, include/wd_dae.h, include/wd_util.h, libwd_dae.map, wd_agg.c, wd_util.c
Weili Qian (1):
drv/dae: support hashagg algorithm
Wenkai Lin (1):
uadk: support for the DAE algorithm layer
Makefile.am              |   28 +-
drv/hisi_dae.c           | 1686 ++++++++++++++++++++++++++++++++++++++
drv/hisi_qm_udrv.h       |    1 +
include/drv/wd_agg_drv.h |   56 ++
include/wd_agg.h         |  233 ++++++
include/wd_alg.h         |    3 +
include/wd_dae.h         |   80 ++
include/wd_util.h        |    1 +
libwd_dae.map            |   21 +
wd_agg.c                 | 1572 +++++++++++++++++++++++++++++++++++
wd_util.c                |    2 +
11 files changed, 3680 insertions(+), 3 deletions(-)
create mode 100644 drv/hisi_dae.c
create mode 100644 include/drv/wd_agg_drv.h
create mode 100644 include/wd_agg.h
create mode 100644 include/wd_dae.h
create mode 100644 libwd_dae.map …
=> support data analysis engine (DAE)

uadk_tool/benchmark/hpre_uadk_benchmark.c, uadk_tool/benchmark/sec_uadk_benchmark.c, uadk_tool/benchmark/zip_uadk_benchmark.c
wd_xxx_init2 does not take para cparam, which take ctx number. So default ctx number is used with poor performance.
numactl --cpubind=0 --membind=0 \
uadk_tool benchmark --alg sha512 --mode sva --opt 0 --async --pktlen 8192 \ --seconds 20 --multi 1 --thread 8 --ctxnum 8 --init2
sha512          8192Bytes       3982625.60KiB/s 497.8Kops       1292.90%
after fix:
numactl --cpubind=0 --membind=0 \
uadk_tool benchmark --alg sha512 --mode sva --opt 0 --async --pktlen 8192 \ --seconds 20 --multi 1 --thread 8 --ctxnum 8 --init2
sha512          8192Bytes       11276124.40KiB/s  1409.5Kops    1026.70%
=> uadk_tool: use wd_xxx_init2_ instead of wd_xxx_init2

Makefile.am, configure.ac, docs/ReleaseNotes.md
=> uadk: release 2.8

drv/hash_mb/hash_mb.c, drv/hisi_comp.c, drv/hisi_dae.c, drv/hisi_hpre.c, drv/hisi_sec.c, drv/isa_ce_sm3.c, drv/isa_ce_sm4.c, include/uacce.h, include/wd.h, include/wd_digest.h, uadk_tool/benchmark/hpre_wd_benchmark.c, uadk_tool/benchmark/sec_wd_benchmark.c, uadk_tool/benchmark/zip_wd_benchmark.c, v1/drv/hisi_qm_udrv.c, v1/drv/hisi_zip_udrv.c, v1/wd.c, v1/wd.h, v1/wd_adapter.c, v1/wd_aead.c, v1/wd_dh.c, v1/wd_ecc.c, v1/wd_rsa.c, v1/wd_sgl.c, v1/wd_util.c, wd_alg.c, wd_comp.c, wd_dh.c, wd_ecc.c, wd_rsa.c, wd_util.c
Chenghai Huang (7):
uadk - fix an req status issue in uadk comp sync2
uadk - add hisi_comp_buf in ctx_buf for internal store buf
uadk - adjust the io buf size ratio
uadk - fix the uninitialized structure issue
uadk - add hisi_zip_buf in ctx_buf for internal store buf
uadk - add condition to adjust the IO buffer ratio condition
uadk - fix sess reset issue
uadk-fix-the-lz77-data-error-issue
Longfang Liu (4):
uadk/v1: fix some code bugs
uadk: update driver code issues
uadk: bugfix UADK inspection issue.
uadk: bugfix SM4 algorithm instruction registration
Qi Tao (2):
uadk: fix cleancode issues
uadk: fix cleancode issues
Weili Qian (4):
drv/dae: remove unneed default branch
uadk/v1: check pointer before memcpy
uadk: check pointer before memcpy
Wenkai Lin (3):
uadk: fix for aead soft compute …
=> uadk: support new algs and fix some cleancode issues

wd_zlibwrapper.c
Add "break" in switch-case statement.
=> uadk: fix switch-case statement error

Makefile.am, configure.ac, docs/ReleaseNotes.md
=> uadk: release 2.9

Makefile.am, configure.ac, docs/ReleaseNotes.md
Release 2.9.1 in 2025.7
Fix x86 build issues
=> uadk: release 2.9.1

Makefile.am, drv/hisi_dae.c, drv/hisi_dae.h, drv/hisi_dae_common.c, drv/hisi_dae_join_gather.c, drv/hisi_qm_udrv.h, drv/hisi_udma.c, include/drv/wd_agg_drv.h, include/drv/wd_join_gather_drv.h, include/drv/wd_udma_drv.h, include/wd_agg.h, include/wd_alg.h, include/wd_dae.h, include/wd_join_gather.h, include/wd_udma.h, include/wd_util.h, libwd_dae.map, wd_agg.c, wd_comp.c, wd_join_gather.c, wd_udma.c, wd_util.c
Weili Qian (1):
uadk: support data move
Zhushuai Yin (5):
uadk: Add max and min operations at the hash algorithm layer
uadk: hash agg adapter drv parameter
uadk:Add max,min,and rehash implementations
uadk:zip algorithm increases buffer len interception
uadk:fix the potential stack overflow issue in dh prov
Wenkai Lin (2):
uadk: fix for rehash invalid size
uadk: support hashjoin and gather algorithm
=> uadk: support udma, hashjoin and gather algorithm
